/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as NewAnalysisRouteImport } from './routes/new-analysis'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ApiAiAdviceRouteImport } from './routes/api/ai-advice'
import { Route as ResultsIdRouteImport } from './routes/results.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAnalysisRoute = NewAnalysisRouteImport.update({
  id: '/new-analysis',
  path: '/new-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAdviceRoute = ApiAiAdviceRouteImport.update({
  id: '/api/ai-advice',
  path: '/api/ai-advice',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIdRoute = ResultsIdRouteImport.update({
  id: '/results/$id',
  path: '/results/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/api/ai-advice': typeof ApiAiAdviceRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/api/ai-advice': typeof ApiAiAdviceRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/materials': typeof MaterialsRoute
  '/new-analysis': typeof NewAnalysisRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/api/ai-advice': typeof ApiAiAdviceRoute
  '/results/$id': typeof ResultsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/history'
    | '/materials'
    | '/new-analysis'
    | '/profile'
    | '/reports'
    | '/api/ai-advice'
    | '/results/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/materials'
    | '/new-analysis'
    | '/profile'
    | '/reports'
    | '/api/ai-advice'
    | '/results/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/history'
    | '/materials'
    | '/new-analysis'
    | '/profile'
    | '/reports'
    | '/api/ai-advice'
    | '/results/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  MaterialsRoute: typeof MaterialsRoute
  NewAnalysisRoute: typeof NewAnalysisRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ApiAiAdviceRoute: typeof ApiAiAdviceRoute
  ResultsIdRoute: typeof ResultsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-analysis': {
      id: '/new-analysis'
      path: '/new-analysis'
      fullPath: '/new-analysis'
      preLoaderRoute: typeof NewAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-advice': {
      id: '/api/ai-advice'
      path: '/api/ai-advice'
      fullPath: '/api/ai-advice'
      preLoaderRoute: typeof ApiAiAdviceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/$id': {
      id: '/results/$id'
      path: '/results/$id'
      fullPath: '/results/$id'
      preLoaderRoute: typeof ResultsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  MaterialsRoute: MaterialsRoute,
  NewAnalysisRoute: NewAnalysisRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ApiAiAdviceRoute: ApiAiAdviceRoute,
  ResultsIdRoute: ResultsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
